# Site settings
title: BY Blog
SEOTitle: 胡钰婷的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: 996950411@qq.com
description: "You've got to ask yourself one question:″Do I feel lucky?″Well,do ya,punk?."
keyword: "BY, BY Blog, 胡钰婷的博客, HUYUTING0903, 胡钰婷, iOS, Apple, iPhone"
url: "http://HUYUTING0903.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/HUYUTING0903/HUYUTING0903.github.io.git" # you code repository


theme: jekyll-theme-merlot